locale: en

title: Sailor

url: https://wizonqalabs.github.io

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

include:
  - _pages

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      permalink: /blogs/:title
      layout: post

webrick:
  headers:
    Access-Control-Allow-Origin: "*"