locale: en-US
title: Sailor
url: https://wizonqalabs.github.io
breadcrumbs: true
address:
  map_url: https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621
  line1: A108 Adam Street
  line2: NY 535022
  city: New York
  city_abbr: NY
  pin: 535022
  country: USA
contact:
  code: "+1"
  phone: 5589 55488 55
  email: info@example.com
footer:
  newsletter_msg: Tamen quem nulla quae legam multos aute sint culpa legam noster magna
  services:
    - name: Web Design
      url: "#"
    - name: Web Development
      url: "#"
    - name: Product Management
      url: "#"
    - name: Marketing
      url: "#"
    - name: Graphic Design
      url: "#"
  social_links:
    - name: twitter
      url: "#"
    - name: facebook
      url: "#"
    - name: instagram
      url: "#"
    - name: google-plus
      class: skype
      url: "#"
    - name: linkedin
      url: "#"
  useful_links:
    - name: Home
      url: "/"
    - name: About us
      url: "/about"
    - name: Services
      url: "/services"
    - name: Terms of service
      url: "#"
    - name: Privacy policy
      url: "#"
stylesheeets:
  - /assets/vendor/bootstrap/css/bootstrap.min.css
  - /assets/vendor/icofont/icofont.min.css
  - /assets/vendor/boxicons/css/boxicons.min.css
  - /assets/vendor/animate.css/animate.min.css
  - /assets/vendor/remixicon/remixicon.css
  - /assets/vendor/venobox/venobox.css
  - /assets/vendor/owl.carousel/assets/owl.carousel.min.css
  - /assets/css/style.css
scripts:
  - /assets/vendor/jquery/jquery.min.js
  - /assets/vendor/bootstrap/js/bootstrap.bundle.min.js
  - /assets/vendor/jquery.easing/jquery.easing.min.js
  - /assets/vendor/php-email-form/validate.js
  - /assets/vendor/isotope-layout/isotope.pkgd.min.js
  - /assets/vendor/venobox/venobox.min.js
  - /assets/vendor/waypoints/jquery.waypoints.min.js
  - /assets/vendor/owl.carousel/owl.carousel.min.js
  - /assets/js/main.js

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

include:
  - _pages

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      permalink: /blogs/:title
      layout: post

webrick:
  headers:
    Access-Control-Allow-Origin: "*"